<?php

namespace Base\Helper;
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class Request extends SymfonyRequest {
	/**
	 * @param bool $asResource
	 * @return string
	 */
	public function getContent($asResource = false) {
		parent::getContent($asResource); // TODO: Change the autogenerated stub
		if (null == $this->content || false === $this->content) {
			$this->content = Request::getInstance()->getRequest()->getSwooleRequest()->rawContent();
			// var_dump($this->content);
		}
		return $this->content;
	}

	public static function clearRequestFactory() {
		self::$requestFactory = null;
	}
}